#please do not edit this file, it is used for automated testing

import resizeAndAddLogo, os
from PIL import Image

def testDirectories():
    initialDirectory = os.getcwd()
    os.chdir('withLogo')
    assert (os.getcwd() == os.path.join(initialDirectory,'withLogo'))

def testTotalFiles():
    os.chdir('../')
    files=0

    for filenames in os.listdir('withLogo'):
        if filenames.endswith('.png') or filenames.endswith('.jpg'):
            files += 1

    assert files == 5

def testSizes():
    for filenames in os.listdir('withLogo'):
        if filenames.endswith('.png') or filenames.endswith('.jpg'):
            im = Image.open( os.path.join('withLogo', filenames ) )
            width, height = im.size
            assert width == 300

def testForOctocat():
    for filenames in os.listdir('withLogo'):
        if filenames.endswith('.png') or filenames.endswith('.jpg'):
            im = Image.open( os.path.join('withLogo', filenames ) )
            width, height = im.size
            assert im.getpixel((width-55,height-80))[2] == 0
